### ISSUE TITLE
Pressing "L" at leaf file should open file in buffer

### ISSUE THREAD

**Issue by ldelossa** [mcchrish/nnn.vim#37]
**Is your feature request related to a problem? Please describe.**
I am not sure this is a "problem" but more (I think) how nnn works outside of nnn.vim

A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

When browsing through the filesystem using "H" and "L" when we reach a leaf file in the tree pressing "L" opens the system's default editor for the file type. I would assume most people are expecting the file to open in a (n)vim buffer. 

**Describe the solution you'd like**
The file is opened in a vim buffer

**Comment by mcchrish** [comment]
This seems to be out of scope of the plugin since the nnn program handles the keybind *and* the context of the navigation. This behavior surprises me as well so I disable it by passing NNN environment variable to the command `let g:nnn#command = 'DISABLE_FILE_OPEN_ON_NAV=1 nnn'` or `let $DISABLE_FILE_OPEN_ON_NAV=1` in vimrc.

**Comment by mcchrish** [comment]
You may take a look at the nnn documentation and see if you can configure nnn to your likings. https://github.com/jarun/nnn#configuration

**Comment by ldelossa** [comment]
@mcchrish did this stop working in recent releases? I have that config in my vimrc but nnn.vim seems to open the file regardless.

**Comment by mcchrish** [comment]
The environment variable was changed to something else in nnn v2.3 it seems:
https://github.com/mcchrish/nnn.vim#environment-variables
