### ISSUE TITLE
Enabling mouse causes window to become unresponsive

### ISSUE THREAD

**Issue by medwatt** [mcchrish/nnn.vim#86]
I was having an issue that when nnn is loaded in (neo)vim and I switch focus to some other window/buffer, the nnn window/buffer becomes unresponsive. I tracked down the issue to the mouse being enabled in normal mode. Normally, I have the mouse enabled in all modes: `set mouse=a`. While disabling the mouse solves the issue, it is not a good solution.

I came up with this workaround:

```vim
autocmd! FileType nnn
autocmd  FileType nnn set mouse=
  \| autocmd BufLeave <buffer> set mouse=a
```

This seems to solve the issue, but I think there could be a better solution. There's also the issue that scrolling with the mouse jumps 3 lines at a time. I tried by explicitly setting `nnn -l 1`, but this didn't seem to have any effect.

![](https://i.imgur.com/w2QOtig.gif)

**Comment by mcchrish** [comment]
@medwatt it seem if you use mouse to focus on the nnn window it only goes into normal mode instead of insert mode.
It's probably not related to mouse input at all as the default behavior of moving the focus to terminal buffer is to start in normal mode.

I personally like to start in insert mode whenever entering the terminal buffer. https://github.com/mcchrish/dotfiles/blob/master/vim/Library/Preferences/nvim/after/plugin/keys.vim#L99-L100

**Comment by medwatt** [comment]
@mcchrish,

**Comment by medwatt** [comment]
@mcchrish, the solution you mentioned doesn't solve the issue.

![](https://i.imgur.com/vF9vnmR.gif)

**Comment by mizlan** [comment]
If you have `set mouse=a` then you should be getting the three-lines-at-a-time scroll. And this should be happening with all buffers, not just the `nnn` buffer. If you have `set mouse=` then you should be getting a smoother line-by-line movement of the cursor.

Unfortunately, since the `mouse` option is global, it makes it very clunky, and your `autocmd` solution does not work when your focus is in one window but your mouse pointer is trying to scroll through the `nnn` window and vice versa. I would have to say that disabling mouse is the most consistent fix here.

**Comment by jarun** [comment]
Closing the issue with the above response. This is not an `nnn` issue.

**Comment by snide** [comment]
@medwatt Just wanted to say thank you for your solution. This was bugging me and I couldn't figure it out. Been living with it for months, and then figured... lemme try and fix it. Your solution works great for me, because I don't need to use my mouse when I'm in the nnn window.
